server.port=8081
spring.profiles.active=dev

# MySQL Database Configuration
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
#swagger configuration
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.url=/v3/api-docs
springdoc.swagger-ui.tryItOutEnabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.swagger-ui.filter=true
springdoc.swagger-ui.syntaxHighlight.activated=true
springdoc.swagger-ui.tagsSorter=alpha

# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true


# MySQL specific properties
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000




spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.serialization.fail-on-empty-beans=false
spring.jackson.deserialization.fail-on-unknown-properties=false
spring.jackson.parser.allow-unquoted-control-chars=true

# File Upload Configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.file-size-threshold=2KB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=15MB

# File Storage Properties
file.upload-dir=./uploads/images

# JWT Configuration
jwt.secret=2983hjd823jd8u83ej23uj823984382i3k9ue2839uu38udj909i43jie2099i3j823u39e939i9e
jwt.expiration-ms=3600000
jwt.refresh-expiration-ms=2592000000
jwt.issuer=mylstech

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=uzairuddin7470@gmail.com
spring.mail.password=deghsxbkdstadiac
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

otp.expiry.minutes=5

zrok.url=https://jce31atrnfrd.share.zrok.io